version: '3.8'

services:
  monomap-api:
    container_name: monomap-api
    image: iscampoos/monomapapi:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: ${MONGO_URL_DOCKER}
      PORT: ${PORT}
      MAIL_SECRET_KEY: ${MAIL_SECRET_KEY}
      MAIL_SERVICE: ${MAIL_SERVICE}
      MAIL_USER: ${MAIL_USER}
      MAPBOX_TOKEN: ${MAPBOX_TOKEN}
  mongo:
    image: mongo
    container_name: mongo-monomap
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27017"
    volumes:
      - mongodb_volume:/data/db

volumes:
  mongodb_volume: