version: '3.8'

services:
  # monomap-api:
  #   container_name: monomap-api
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongo
  #   environment:
  #     PORT: ${PORT}
  #     MONGO_URL_DOCKER: ${MONGO_URL_DOCKER}
  mongo:
    image: mongo
    container_name: mongo-monomap
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27017"
    volumes:
      - mongodb_volume:/data/db

volumes:
  mongodb_volume: